import type {
  AdminDashboardResponse,
  SalesDashboardResponse,
  InspectorDashboardResponse,
  FinanceDashboardResponse,
  StoreManagerDashboardResponse,
} from "../types";

export const mockAdminDashboard: AdminDashboardResponse = {
  overview: {
    totalCars: 245,
    availableCars: 87,
    reservedCars: 23,
    soldCarsThisMonth: 34,
    activeInquiries: 56,
    activeReservations: 23,
    totalEmployees: 48,
    activeEmployees: 42,
  },
  revenue: {
    totalRevenue: 8750000,
    monthlyRevenue: 1250000,
    ytdRevenue: 6500000,
    averageSalePrice: 35000,
    revenueTrend: [
      { month: 7, monthName: "Jul", revenue: 980000, salesCount: 28 },
      { month: 8, monthName: "Aug", revenue: 1150000, salesCount: 32 },
      { month: 9, monthName: "Sep", revenue: 890000, salesCount: 25 },
      { month: 10, monthName: "Oct", revenue: 1320000, salesCount: 38 },
      { month: 11, monthName: "Nov", revenue: 1100000, salesCount: 31 },
      { month: 12, monthName: "Dec", revenue: 1250000, salesCount: 34 },
    ],
  },
  inventory: {
    byStatus: {
      AVAILABLE: 87,
      RESERVED: 23,
      SOLD: 34,
      IN_MAINTENANCE: 12,
      IN_TRANSIT: 15,
      INSPECTION_REQUIRED: 8,
    },
    totalValue: 18500000,
    avgAge: 42,
    agingInventory: [
      {
        carId: 1,
        make: "Toyota",
        model: "Camry",
        year: 2022,
        daysInInventory: 120,
        purchasePrice: 28000,
      },
      {
        carId: 2,
        make: "Honda",
        model: "Accord",
        year: 2021,
        daysInInventory: 95,
        purchasePrice: 26500,
      },
      {
        carId: 3,
        make: "Ford",
        model: "F-150",
        year: 2023,
        daysInInventory: 87,
        purchasePrice: 45000,
      },
    ],
  },
  recentActivities: [
    {
      id: 1,
      type: "SALE",
      description: "Vehicle sold - 2023 Tesla Model 3",
      entityType: "CAR",
      entityId: 145,
      timestamp: "2025-12-24T10:30:00Z",
      performedBy: "John Smith",
    },
    {
      id: 2,
      type: "RESERVATION",
      description: "New reservation - 2024 BMW X5",
      entityType: "RESERVATION",
      entityId: 89,
      timestamp: "2025-12-24T09:15:00Z",
      performedBy: "Sarah Johnson",
    },
    {
      id: 3,
      type: "INSPECTION",
      description: "Inspection completed - 2022 Mercedes C-Class",
      entityType: "INSPECTION",
      entityId: 234,
      timestamp: "2025-12-24T08:45:00Z",
      performedBy: "Mike Davis",
    },
    {
      id: 4,
      type: "INQUIRY",
      description: "New inquiry - Customer interested in SUVs",
      entityType: "INQUIRY",
      entityId: 567,
      timestamp: "2025-12-23T16:20:00Z",
      performedBy: "Emily Chen",
    },
  ],
  topEmployees: [
    {
      employeeId: 1,
      employeeName: "John Smith",
      position: "Senior Sales Executive",
      salesCount: 12,
      totalCommission: 18000,
      totalRevenue: 450000,
    },
    {
      employeeId: 2,
      employeeName: "Sarah Johnson",
      position: "Sales Executive",
      salesCount: 9,
      totalCommission: 13500,
      totalRevenue: 315000,
    },
    {
      employeeId: 3,
      employeeName: "Michael Brown",
      position: "Sales Executive",
      salesCount: 8,
      totalCommission: 12000,
      totalRevenue: 280000,
    },
    {
      employeeId: 4,
      employeeName: "Emily Chen",
      position: "Junior Sales Executive",
      salesCount: 5,
      totalCommission: 7500,
      totalRevenue: 175000,
    },
  ],
  alerts: {
    expiringReservations: 5,
    inspectionsDue: 8,
    locationCapacityWarnings: 2,
    details: [
      {
        type: "RESERVATION",
        message: "5 reservations expiring in 48 hours",
        severity: "WARNING",
      },
      {
        type: "INSPECTION",
        message: "8 vehicles require immediate inspection",
        severity: "ERROR",
      },
      {
        type: "CAPACITY",
        message: "Location A near full capacity (95%)",
        severity: "WARNING",
      },
    ],
  },
  notifications: {
    unreadCount: 12,
    recent: [
      {
        id: 1,
        type: "SALE",
        subject: "Sale Completed",
        body: "Vehicle #145 sold for $42,000",
        entityType: "SALE",
        entityId: 145,
        severity: "INFO",
        createdAt: "2025-12-24T10:30:00Z",
        isRead: false,
      },
      {
        id: 2,
        type: "RESERVATION",
        subject: "New Reservation",
        body: "Customer reserved Vehicle #234",
        entityType: "RESERVATION",
        entityId: 234,
        severity: "INFO",
        createdAt: "2025-12-24T09:15:00Z",
        isRead: false,
      },
      {
        id: 3,
        type: "ALERT",
        subject: "Inspection Overdue",
        body: "Vehicle #456 inspection overdue by 3 days",
        entityType: "INSPECTION",
        entityId: 456,
        severity: "WARNING",
        createdAt: "2025-12-23T14:20:00Z",
        isRead: false,
      },
    ],
  },
};

export const mockSalesDashboard: SalesDashboardResponse = {
  personalStats: {
    activeInquiries: 15,
    convertedInquiries: 8,
    activeReservations: 5,
    salesThisMonth: 9,
    commissionEarned: 13500,
    conversionRate: 53.3,
  },
  pipeline: {
    inquiriesByStatus: {
      NEW: 5,
      CONTACTED: 7,
      NEGOTIATING: 3,
      RESERVED: 5,
      CLOSED: 8,
    },
    followUpToday: 4,
    followUpThisWeek: 11,
  },
  performance: {
    monthlySales: 9,
    monthlyTarget: 12,
    targetProgress: 75,
    avgSaleValue: 35000,
  },
  quickActions: {
    pendingResponses: 6,
    followUpsDue: 4,
    expiringReservations: 2,
    items: [
      {
        id: 1,
        type: "FOLLOW_UP",
        description: "Follow up with John Doe about 2023 Tesla",
        priority: "HIGH",
        dueDate: "2025-12-24T17:00:00Z",
      },
      {
        id: 2,
        type: "RESPONSE",
        description: "Respond to inquiry about BMW X5",
        priority: "HIGH",
        dueDate: "2025-12-24T15:00:00Z",
      },
      {
        id: 3,
        type: "RESERVATION",
        description: "Confirm reservation expiring tomorrow",
        priority: "MEDIUM",
        dueDate: "2025-12-25T10:00:00Z",
      },
    ],
  },
  availableInventory: {
    totalAvailable: 87,
    newArrivals: 12,
    featured: [
      { id: 1, make: "Tesla", model: "Model 3", year: 2023, price: 42000 },
      { id: 2, make: "BMW", model: "X5", year: 2024, price: 65000 },
      { id: 3, make: "Mercedes", model: "C-Class", year: 2023, price: 48000 },
    ],
  },
  notifications: {
    unreadCount: 8,
    recent: [
      {
        id: 1,
        type: "INQUIRY",
        subject: "New Inquiry",
        body: "Customer interested in luxury sedans",
        entityType: "INQUIRY",
        entityId: 123,
        severity: "INFO",
        createdAt: "2025-12-24T11:30:00Z",
        isRead: false,
      },
      {
        id: 2,
        type: "FOLLOW_UP",
        subject: "Follow-up Due",
        body: "Follow up with customer from last week",
        entityType: "INQUIRY",
        entityId: 98,
        severity: "WARNING",
        createdAt: "2025-12-24T09:00:00Z",
        isRead: false,
      },
    ],
  },
};

export const mockInspectorDashboard: InspectorDashboardResponse = {
  inspectionQueue: {
    pendingInspections: 18,
    scheduledToday: 5,
    scheduledThisWeek: 12,
    overdue: 3,
  },
  personalStats: {
    completedThisMonth: 45,
    passRate: 82.5,
    avgInspectionTime: 2.5,
    avgRepairCost: 850,
  },
  vehicleStatus: {
    needingInspection: 18,
    failedInspections: 6,
    inMaintenance: 12,
  },
  assignedTasks: {
    total: 23,
    highPriority: 7,
    dueToday: 5,
  },
  locationSummary: [
    {
      locationName: "Downtown Location",
      pendingCount: 8,
      completedThisWeek: 15,
    },
    {
      locationName: "North Branch",
      pendingCount: 5,
      completedThisWeek: 12,
    },
    {
      locationName: "South Branch",
      pendingCount: 5,
      completedThisWeek: 18,
    },
  ],
  recentInspections: [
    {
      id: 1,
      carId: 145,
      carDetails: "2023 Toyota Camry",
      status: "PASSED",
      completedAt: "2025-12-24T10:00:00Z",
      findings: "Minor wear on brake pads",
    },
    {
      id: 2,
      carId: 234,
      carDetails: "2022 Honda Accord",
      status: "FAILED",
      completedAt: "2025-12-24T08:30:00Z",
      findings: "Requires engine diagnostics",
    },
    {
      id: 3,
      carId: 189,
      carDetails: "2024 Ford F-150",
      status: "PASSED",
      completedAt: "2025-12-23T16:45:00Z",
      findings: "Excellent condition",
    },
  ],
  notifications: {
    unreadCount: 6,
    recent: [
      {
        id: 1,
        type: "INSPECTION",
        subject: "Urgent Inspection",
        body: "High-priority vehicle requires immediate inspection",
        entityType: "INSPECTION",
        entityId: 567,
        severity: "ERROR",
        createdAt: "2025-12-24T09:00:00Z",
        isRead: false,
      },
      {
        id: 2,
        type: "MAINTENANCE",
        subject: "Maintenance Completed",
        body: "Vehicle #234 maintenance work finished",
        entityType: "MAINTENANCE",
        entityId: 234,
        severity: "INFO",
        createdAt: "2025-12-24T08:15:00Z",
        isRead: false,
      },
    ],
  },
};

export const mockFinanceDashboard: FinanceDashboardResponse = {
  financialOverview: {
    totalRevenue: 1250000,
    totalExpenses: 850000,
    netProfit: 400000,
    profitMargin: 32.0,
    cashFlow: 380000,
  },
  transactions: {
    pendingCount: 8,
    completedThisMonth: 156,
    totalAmount: 1250000,
    recentTransactions: [
      { id: 1, type: "SALE", amount: 42000, date: "2025-12-24T10:30:00Z" },
      { id: 2, type: "PURCHASE", amount: -28000, date: "2025-12-24T09:00:00Z" },
      {
        id: 3,
        type: "COMMISSION",
        amount: -1500,
        date: "2025-12-23T16:00:00Z",
      },
    ],
  },
  profitability: {
    avgProfitPerVehicle: 12000,
    avgMargin: 28.5,
    vehicleProfitability: [
      { carId: 1, make: "Tesla", model: "Model 3", profit: 15000, margin: 35 },
      { carId: 2, make: "BMW", model: "X5", profit: 18000, margin: 32 },
      { carId: 3, make: "Honda", model: "Accord", profit: 8000, margin: 25 },
    ],
  },
  aging: {
    overduePayments: 3,
    overdueAmount: 45000,
    pendingDeposits: 5,
  },
  budgetTracking: {
    totalBudget: 500000,
    spent: 380000,
    utilizationRate: 76,
    categories: {
      OPERATIONS: 150000,
      MARKETING: 80000,
      MAINTENANCE: 70000,
      SALARIES: 80000,
    },
  },
  notifications: {
    unreadCount: 5,
    recent: [
      {
        id: 1,
        type: "PAYMENT",
        subject: "Payment Overdue",
        body: "Invoice #1234 overdue by 15 days",
        entityType: "TRANSACTION",
        entityId: 1234,
        severity: "WARNING",
        createdAt: "2025-12-24T10:00:00Z",
        isRead: false,
      },
      {
        id: 2,
        type: "DEPOSIT",
        subject: "Deposit Received",
        body: "Customer deposit of $5,000 received",
        entityType: "TRANSACTION",
        entityId: 5678,
        severity: "INFO",
        createdAt: "2025-12-24T09:30:00Z",
        isRead: false,
      },
    ],
  },
};

export const mockStoreManagerDashboard: StoreManagerDashboardResponse = {
  locationOverview: {
    totalLocations: 5,
    totalCapacity: 350,
    currentOccupancy: 245,
    utilizationRate: 70,
  },
  vehicleDistribution: {
    byLocation: {
      "Downtown Location": 78,
      "North Branch": 65,
      "South Branch": 52,
      "East Branch": 32,
      "West Branch": 18,
    },
    byStatus: {
      AVAILABLE: 87,
      RESERVED: 23,
      IN_MAINTENANCE: 12,
      IN_TRANSIT: 15,
      INSPECTION_REQUIRED: 8,
    },
  },
  movements: {
    todayMovements: 8,
    thisWeekMovements: 34,
    recentMovements: [
      {
        id: 1,
        vehicleId: 145,
        from: "Downtown Location",
        to: "North Branch",
        timestamp: "2025-12-24T10:30:00Z",
      },
      {
        id: 2,
        vehicleId: 234,
        from: "South Branch",
        to: "Downtown Location",
        timestamp: "2025-12-24T09:15:00Z",
      },
      {
        id: 3,
        vehicleId: 189,
        from: "East Branch",
        to: "West Branch",
        timestamp: "2025-12-24T08:45:00Z",
      },
    ],
  },
  capacityAlerts: {
    nearFullLocations: 1,
    underutilizedLocations: 2,
    details: [
      {
        location: "Downtown Location",
        capacity: 80,
        occupancy: 78,
        utilizationRate: 97.5,
        status: "NEAR_FULL",
      },
      {
        location: "West Branch",
        capacity: 50,
        occupancy: 18,
        utilizationRate: 36,
        status: "UNDERUTILIZED",
      },
    ],
  },
  maintenanceStatus: {
    vehiclesInMaintenance: 12,
    avgMaintenanceTime: 3.2,
    upcomingMaintenance: 8,
  },
  performance: {
    avgTurnoverDays: 38,
    avgStayDuration: 42,
    topPerformingLocations: [
      { location: "Downtown Location", turnoverDays: 28, salesCount: 45 },
      { location: "North Branch", turnoverDays: 35, salesCount: 38 },
      { location: "South Branch", turnoverDays: 42, salesCount: 32 },
    ],
  },
  notifications: {
    unreadCount: 7,
    recent: [
      {
        id: 1,
        type: "CAPACITY",
        subject: "Capacity Alert",
        body: "Downtown Location at 97% capacity",
        entityType: "LOCATION",
        entityId: 1,
        severity: "WARNING",
        createdAt: "2025-12-24T11:00:00Z",
        isRead: false,
      },
      {
        id: 2,
        type: "MOVEMENT",
        subject: "Vehicle Transfer",
        body: "Vehicle #145 moved to North Branch",
        entityType: "MOVEMENT",
        entityId: 145,
        severity: "INFO",
        createdAt: "2025-12-24T10:30:00Z",
        isRead: false,
      },
    ],
  },
};
